# Harry Potter Dataset
## Data Wrangling: Joining & Combining Data

<img src='hogwarts.JPG'>
<i>Image by inspiredbythemuse from <a href="https://pixabay.com/illustrations/hogwarts-owl-hedwig-harry-potter-2036645/">Pixabay</a></i>

Now we will look more into joining and combining data. It is often the case where you need to combine data from various sources for further analysis.

In this notebook, you will use a number of Harry Potter related datasets to practice data manipulation. First, download the notebook and the Excel file titled `harry_potter.xlsx` and place them in the same folder. 

Also note that there are sometimes different ways to do the same thing when using Python and Pandas for data manipulation. Some ways are more efficient than others, especially with larger data sets, but since these datasets are so small, the suggested solutions may not be the most efficient. Instead, our goal is to show you different options when it comes to completing the tasks.

The complete set of Harry Potter datasets can be found here: [Kaggle](https://www.kaggle.com/gulsahdemiryurek/harry-potter-dataset)

### Initial Imports

In [2]:
# import common Libraries
import pandas as pd
import numpy as np

In [4]:
 # import data from Excel 
fileName = "harry_potter.xlsx" #ensure file is in same location as notebook or add path

# create ExcelFile object
xls = pd.ExcelFile(fileName)

# load individual sheets / we'll explain the data as we go along
gryffindor = pd.read_excel(xls, 'gryffindor', index_col='ID')
slytherin = pd.read_excel(xls, 'slytherin', index_col='ID')
hufflepuff = pd.read_excel(xls, 'hufflepuff', index_col='ID')
ravenclaw = pd.read_excel(xls, 'ravenclaw', index_col='ID')
other1 = pd.read_excel(xls, 'other1', index_col='ID')
other2 = pd.read_excel(xls, 'other2', index_col='ID')
loyalty = pd.read_excel(xls, 'loyalty', index_col='ID')
dead_characters = pd.read_excel(xls, 'dead_characters', index_col='ID')
gryffindor_bloodstatus = pd.read_excel(xls, 'gryffindor_bloodstatus', index_col='ID')
gryffindor_species = pd.read_excel(xls, 'gryffindor_species', index_col='ID')
color = pd.read_excel(xls, 'color', index_col='ID')
wand = pd.read_excel(xls, 'wand', index_col='ID')

Let's take a look at the first dataset: `gryffindor`

In [6]:
gryffindor.head()

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood


Let's also take a closer look at the `Species` attribute.

In [8]:
gryffindor['Species'].value_counts()

Species
Human                      36
Human                       3
Werewolf                    1
Human (Werewolf traits)     1
Ghost                       1
Name: count, dtype: int64

Notice that there are two values labeled `Human`. Why is that?

This happens a lot when loading messy datasets (especially with Excel files) where there can be either leading or trailing spaces. There are a couple of ways to clean this up, and one of the easiest ways is to use the `strip()` method.

#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

**Exercise:** Use the `strip()` method to remove leading or trailing spaces from the `Species` attribute. Print the value counts for the `Species` column to double check your work.

In [14]:
### ENTER CODE HERE ###

gryffindor['Species']=gryffindor['Species'].str.strip()

Species
Human                      39
Werewolf                    1
Human (Werewolf traits)     1
Ghost                       1
Name: count, dtype: int64

Good. That took care of the trailing spaces for this column. We can now create a function to remove leading and trailing spaces from all columns of their respective DataFrames. 

**Bonus Exercise:** Create a function called `whitespace` that takes as input a list of the Harry Potter DataFrames. This function should strip the leading and trailing spaces from each column that has an `object` data type for each DataFrame.

In [18]:
### ENTER CODE HERE ###
df_list= [gryffindor, slytherin,hufflepuff, ravenclaw,other1,other2,
          loyalty, dead_characters,gryffindor_bloodstatus,gryffindor_species,color,wand]

def whitespace (df_list):
    for df in df_list:
        for col in df.columns:
            if df[col].dtype == 'object':
                df[col] = df[col].str.strip()

whitespace(df_list)

### Adding Rows

#### Concat

Panda's [concat()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) method can be used for simple concatenation of arrays and dataframes along a particular axis. One important thing to note is that Pandas concatenation preserves indices, even if the result will have duplicate indices. We'll see this more in a moment.

In [20]:
# create a simple dataset
df1 = pd.DataFrame({'a': [1,2,3,4],
                  'b': [5,6,7,8]})

df1

,a,b
0,1,5
1,2,6
2,3,7
3,4,8


In [22]:
# create another simple dataset
df2 = pd.DataFrame({'a': [9,10,11,12],
                  'b': [13,14,15,16]})
df2

,a,b
0,9,13
1,10,14
2,11,15
3,12,16


In [24]:
# using concat
pd.concat([df1,df2])

,a,b
0,1,5
1,2,6
2,3,7
3,4,8
0,9,13
1,10,14
2,11,15
3,12,16


In [26]:
# using axis=1
pd.concat([df1,df2], axis=1)

,a,b,a,b
0,1,5,9,13
1,2,6,10,14
2,3,7,11,15
3,4,8,12,16


In [28]:
# can pass keys for multi-index
pd.concat([df1,df2], axis=1, keys=['key1', 'key2'])

key1    key2    
     a  b    a   b
0    1  5    9  13
1    2  6   10  14
2    3  7   11  15
3    4  8   12  16

Let's review basic outer vs inner joins.

In [30]:
# create another DataFrame 
df3 = pd.DataFrame({'a': [17,18,19,20],
                  'c': [21,22,23,24]})
df3

,a,c
0,17,21
1,18,22
2,19,23
3,20,24


In [32]:
# outer join (df1 union df3)
pd.concat([df1,df3], join='outer')

,a,b,c
0,1,5.0,NaN
1,2,6.0,NaN
2,3,7.0,NaN
3,4,8.0,NaN
0,17,NaN,21.0
1,18,NaN,22.0
2,19,NaN,23.0
3,20,NaN,24.0


In [34]:
# inner join (df1 intersect df3)
pd.concat([df1,df3], join='inner')

,a
0,1
1,2
2,3
3,4
0,17
1,18
2,19
3,20


You should also notice that the index (in this case) column didn't change with the new DataFrame. This is good in some cases since some indices are unique identifiers. But in some circumstances, you don't want the index to remain the same (for example when you have multiple rows with the same index). In these cases, you could use the `ignore_index=True` argument to reset the indices.

In [36]:
# using default concat method
pd.concat([df1,df2])

,a,b
0,1,5
1,2,6
2,3,7
3,4,8
0,9,13
1,10,14
2,11,15
3,12,16


In [38]:
# using ignore_index=True
pd.concat([df1,df2], ignore_index=True)

,a,b
0,1,5
1,2,6
2,3,7
3,4,8
4,9,13
5,10,14
6,11,15
7,12,16


#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

We now want to create a new DataFrame that contains all the characters from the Harry Potter series. 

*Note: There are easier ways to do this all at once, but we want to call your attention to some things so we will add to this DataFrame a little at a time.*

**Exercise:** Use the `copy()` method to copy the `gryffindor` dataset to a new DataFrame that you will call `hp_characters`.

In [42]:
### ENTER CODE HERE ###

hp_characters = gryffindor.copy()
hp_characters.head()

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood


**Exercise:** Add the `slytherin` dataset to the new `hp_characters` DataFrame using the `concat()` method.  

In [44]:
### ENTER CODE HERE ###

pd.concat([hp_characters, slytherin])

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood
...,...,...,...,...,...,...,...
89,Augustus Rookwood,Male,Unspeakable,Slytherin,NaN,Human,Pure-blood or half-blood
90,Antonin Dolohov,Male,Death Eater,Slytherin,NaN,Human,Pure-blood or Half-blood
91,Corban Yaxley,Male,Head of the Department of Magical Law Enforcement,Slytherin,NaN,Human,Pure-blood or Half-blood


**Exercise**: Add the `ravenclaw` data to `hp_characters` using the `concat` method.

In [46]:
### ENTER CODE HERE ###
pd.concat([hp_characters, ravenclaw])

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood
5,Fred Weasley,Male,Student,Gryffindor,?,Human,Pure-blood
6,George Weasley,Male,Student,Gryffindor,?,Human,Pure-blood
7,Ginevra (Ginny) Molly Weasley,Female,Student,Gryffindor,Horse,Human,Pure-blood
8,Dean Thomas,Male,Student,Gryffindor,?,Human,Muggle-born


Let's now take a look at the last Hogwarts house, Hufflepuff.

In [48]:
# view hufflepuff data
hufflepuff

,Name,Gender,Job,House,Patronus,Species,Blood status,Skills
ID,,,,,,,,
76,Helga Hufflepuff,Female,Founder of Hufflepuff,Hufflepuff,?,Human,Pure-blood or half-blood,Food-related Charms. Many traditional Hogwarts...
77,Fat Friar,Male,Hufflepuff House Ghost,Hufflepuff,?,Ghost,NaN,Curing peasants of the pox
79,Nymphadora Tonks,Female,Auror,Hufflepuff,"Jack rabbit, Wolf",Human,Half-blood,"Talented Auror, Metamorphmagus"
80,Pomona Sprout,Female,Professor of Herbology | Head of Hufflepuff House,Hufflepuff,Non-corporeal,Human,Pure-blood or half-blood,Herbology
81,Newton Scamander,Male,Employee in the Beast Division of the Departme...,Hufflepuff,?,Human,Pure-blood or half-blood,"Magizoology, Order of Merlin, Second Class"
139,Dr. Greg Longo,Male,Professor,Hufflepuff,Eagle,Human,Muggle-born,Can charm others using Muggle statistics
140,Prof. Jeff Eicher,Male,Professor,Hufflepuff,Eagle,Human,Muggle-born,Uses cloud computing to fight Voldemort
82,Cedric Diggory,Male,Student,Hufflepuff,?,Human,Pure-blood,Skilled Seeker
83,Justin Finch-Fletchley,Male,Student,Hufflepuff,Non-corporeal,Human,Muggle-born,NaN


Notice that this DataFrame has an extra attribute, `Skills`. Also, if you look at `ID` 139 and 140, there appears to be some bad data in the file. We'll clean that up in a moment. Let's see what happens when we add this data to the new DataFrame.

**Exercise:** Add `hufflepuff` to the `hp_characters` DataFrame. What happens with the `Skill` column?

In [50]:
### ENTER CODE HERE ###
pd.concat([hp_characters, hufflepuff])

,Name,Gender,Job,House,Patronus,Species,Blood status,Skills
ID,,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,NaN
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,NaN
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,NaN
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,NaN
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,NaN
5,Fred Weasley,Male,Student,Gryffindor,?,Human,Pure-blood,NaN
6,George Weasley,Male,Student,Gryffindor,?,Human,Pure-blood,NaN
7,Ginevra (Ginny) Molly Weasley,Female,Student,Gryffindor,Horse,Human,Pure-blood,NaN
8,Dean Thomas,Male,Student,Gryffindor,?,Human,Muggle-born,NaN


Notice that there is now an extra column titled `Skills`. Pandas automatically added missing values for the instances in the original data since there was not a `Skill` column. Remember that the concat method uses an outer join when combining data.

Now what if instead, we wanted to pull together all four separate dataframes into a new dataframe at one time. Again, there are multiple ways to do this.

**Exercise:** Create a new DataFrame titled `hp_characters2` and add all four DataFrames (`gryffindor`, `slytherin`, `ravenclaw`, and `hufflepuff`) at one time. Try to combine these datasets in one line of code.

In [54]:
### ENTER CODE HERE ###

hp_characters2 = pd.concat([gryffindor, slytherin, ravenclaw, hufflepuff])
hp_characters2.head()

,Name,Gender,Job,House,Patronus,Species,Blood status,Skills
ID,,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,NaN
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,NaN
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,NaN
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,NaN
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,NaN


**Exercise:** Combine all four datasets into a new dataframe called `hp_characters3` using a new index. 

In [62]:
### ENTER CODE HERE ###
hp_characters3 = pd.concat([gryffindor, slytherin, ravenclaw, hufflepuff], ignore_index=True)
hp_characters3.tail()

,Name,Gender,Job,House,Patronus,Species,Blood status,Skills
98,Hannah Abbott,Female,Student,Hufflepuff,Non-corporeal,Human,Half-blood,"Defensive spells, learned with Dumbledore's Army"
99,Ernest Macmillan,Male,Student,Hufflepuff,Boar,Human,Pure-blood,"Revising, being a Prefect, getting the wrong e..."
100,Susan Bones,Female,Student,Hufflepuff,?,Human,Half-blood,"Defensive spells, learned with Dumbledore's Army"
101,Edgar Bones,Male,NaN,Hufflepuff,?,Human,Pure-blood or half-blood,Said to be a great wizard
102,Edward Remus Lupin,Male,Student,Hufflepuff,?,Human (Metamorphmagus),Half-blood,NaN


### Dropping Instances

#### Student Practice
Try to perform the following tasks on the indicated dataset. Then check your answers as I walk through the solutions. 

Using the `hp_characters` dataframe we created, let's practice removing instances from the data.

First, we will remove the two incorrect names that were listed in the `Hufflepuff` house data. Let's view the incorrect names by using their index.

In [68]:
# view incorrect names in dataset
    #hp_characters.loc[[139,140]]

hp_characters


,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood
5,Fred Weasley,Male,Student,Gryffindor,?,Human,Pure-blood
6,George Weasley,Male,Student,Gryffindor,?,Human,Pure-blood
7,Ginevra (Ginny) Molly Weasley,Female,Student,Gryffindor,Horse,Human,Pure-blood
8,Dean Thomas,Male,Student,Gryffindor,?,Human,Muggle-born


**Exercise:** Remove Dr. Longo from the dataset using his `ID` number.

In [70]:
### ENTER CODE HERE ###
hp_characters = hp_characters.drop(139, axis=0)


KeyError: '[139] not found in axis'

In [72]:
# view other incorrect entry
hp_characters[hp_characters['Patronus'] == 'Eagle']

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,


Dr. Longo is now removed from the dataset. Now, let's remove Prof. Eicher by using his name.

**Exercise:** Remove Prof. Eicher from the dataset but this time using his name. Hint: One way is to do this by filtering your data and saving this filtered data as the DataFrame.

In [ ]:
### ENTER CODE HERE ###
hp_characters = hp_characters[hp_characters['Name'] != 'Prof. Jeff Eicher']

In [ ]:
# confirm that entry was removed
hp_characters[hp_characters['Patronus'] == 'Eagle']

Now that we have cleaned those instances, there are some other instances that we need to remove. Take a look at the following:

In [78]:
hp_characters[hp_characters['Patronus'] == 'Lion']

,Name,Gender,Job,House,Patronus,Species,Blood status
ID,,,,,,,


It looks like someone accidentally included Game of Thrones names in the dataset. Let's remove them all at once (there are a number of different ways to do this).

**Exercise:** Remove all instances of Game of Thrones characters from the dataset. Use `inplace=True`.

In [76]:
### ENTER CODE HERE ###
hp_characters.drop([141, 142, 143, 144, 145], inplace=True)

Remember that by using `inplace=True`, you can modify the dataframe without doing an assignment. However, you should be careful when using it. See the links below.

https://stackoverflow.com/questions/45570984/in-pandas-is-inplace-true-considered-harmful-or-not

https://github.com/pandas-dev/pandas/issues/16529

### Adding Columns
So far, we have been adding or removing rows from our DataFrame. Now, let's practice adding columns. 

#### Join
The [join()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html) method joins columns of another DataFrame either on index or on a key column. Let's setup two new DataFrames to check this out.

In [80]:
# create sample DataFrame
df4 = pd.DataFrame({'Animal': ['cat','dog','horse','cow','fox'],
                   'Color': ['white','brown','grey','black','brown']})
df4

,Animal,Color
0,cat,white
1,dog,brown
2,horse,grey
3,cow,black
4,fox,brown


In [82]:
# second sample DataFrame
df5 = pd.DataFrame({'Sound': ['meow','bark','neigh','moo',np.nan]})
df5

,Sound
0,meow
1,bark
2,neigh
3,moo
4,NaN


In [84]:
# join the two DataFrames based on index
df4.join(df5)

,Animal,Color,Sound
0,cat,white,meow
1,dog,brown,bark
2,horse,grey,neigh
3,cow,black,moo
4,fox,brown,NaN


In [86]:
# using concat, axis=1
pd.concat([df4,df5], axis=1)

,Animal,Color,Sound
0,cat,white,meow
1,dog,brown,bark
2,horse,grey,neigh
3,cow,black,moo
4,fox,brown,NaN


In [88]:
# third sample DataFrame but with slightly different index
df6 = pd.DataFrame({'Size': ['small','medium','large','large','huge']}, index=[0,1,2,3,5])
df6

,Size
0,small
1,medium
2,large
3,large
5,huge


In [90]:
# notice index 4 and missing index 5
df4.join(df6)

,Animal,Color,Size
0,cat,white,small
1,dog,brown,medium
2,horse,grey,large
3,cow,black,large
4,fox,brown,NaN


In [92]:
# using how='right'
df4.join(df6, how='right')

,Animal,Color,Size
0,cat,white,small
1,dog,brown,medium
2,horse,grey,large
3,cow,black,large
5,NaN,NaN,huge


#### Merge

See the following regarding the [merge()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) method from the `Python Data Science Handbook`:

> One essential feature offered by Pandas is its high-performance, in-memory join and merge operations. If you have ever worked with databases, you should be familiar with this type of data interaction. The main interface for this is the pd.merge function

> The behavior implemented in `pd.merge()` is a subset of what is known as relational algebra, which is a formal set of rules for manipulating relational data, and forms the conceptual foundation of operations available in most databases. The strength of the relational algebra approach is that it proposes several primitive operations, which become the building blocks of more complicated operations on any dataset. With this lexicon of fundamental operations implemented efficiently in a database or other program, a wide range of fairly complicated composite operations can be performed. Pandas implements several of these fundamental building-blocks in the `pd.merge()` function and the related `join()` method of Series and Dataframes.

In [94]:
# create sample DataFrame
df1 = pd.DataFrame({'lkey': ['fizz', 'buzz', 'fizzbuzz', 'fizz'],
                    'value': [1, 2, 3, 5]})

df1 

,lkey,value
0,fizz,1
1,buzz,2
2,fizzbuzz,3
3,fizz,5


In [96]:
# create other sample DataFrame
df2 = pd.DataFrame({'rkey': ['fizz', 'buzz', 'fizzbuzz', 'fizz'],
                    'value': [5, 6, 7, 8]})
df2

,rkey,value
0,fizz,5
1,buzz,6
2,fizzbuzz,7
3,fizz,8


In [98]:
# merge on 'lkey' and 'rkey' columns
df1.merge(df2, left_on='lkey', right_on='rkey')

,lkey,value_x,rkey,value_y
0,fizz,1,fizz,5
1,fizz,1,fizz,8
2,buzz,2,buzz,6
3,fizzbuzz,3,fizzbuzz,7
4,fizz,5,fizz,5
5,fizz,5,fizz,8


In [100]:
# specifying suffixes to overlapping columns
df1.merge(df2, left_on='lkey', right_on='rkey',
          suffixes=('_left', '_right'))

,lkey,value_left,rkey,value_right
0,fizz,1,fizz,5
1,fizz,1,fizz,8
2,buzz,2,buzz,6
3,fizzbuzz,3,fizzbuzz,7
4,fizz,5,fizz,5
5,fizz,5,fizz,8


In [104]:
# raise an exception if the DataFrames have any overlapping columns.
#df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))

In [106]:
# let's look at another example
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                             'data2': range(3)})

In [108]:
df1

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,a,5
6,b,6


In [110]:
df2

,key,data2
0,a,0
1,b,1
2,d,2


In [112]:
# this is an example of a many-to-one join
# inner join (by default)
pd.merge(df1, df2)

,key,data1,data2
0,b,0,1
1,b,1,1
2,a,2,0
3,a,4,0
4,a,5,0
5,b,6,1


Notice that for every "b" there was a "1" added to the `data2` column and a "0" added for every "a". It also doesn't include "c" from df1 and "d" from df2.

I didn't specify which column to join on so Pandas uses the overlapping column names as the keys. Although it's good practice to specify (`on='key')`

In [114]:
# left outer join
pd.merge(df1, df2, how='left')

,key,data1,data2
0,b,0,1.0
1,b,1,1.0
2,a,2,0.0
3,c,3,NaN
4,a,4,0.0
5,a,5,0.0
6,b,6,1.0


In [ ]:
# right outer join
pd.merge(df1, df2, how='right')

In [ ]:
# full outer join
pd.merge(df1, df2, how='outer')

In [ ]:
# creates the cartesian product from both frames
# preserves the order of the left keys
pd.merge(df1, df2, how='cross', suffixes=('_left','_right'))

In [116]:
# create two simple DataFrames for card suits and card numbers
suits = pd.DataFrame({'suit': ['clubs','hearts','diamonds','spades']
                       })

numbers = pd.DataFrame({'card_number': ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
                       })

In [118]:
suits

,suit
0,clubs
1,hearts
2,diamonds
3,spades


In [120]:
numbers

,card_number
0,A
1,2
2,3
3,4
4,5
5,6
6,7
7,8
8,9
9,10


In [122]:
# what are all the different combination of suits and numbers
deck = pd.merge(suits, numbers, how='cross')
deck

,suit,card_number
0,clubs,A
1,clubs,2
2,clubs,3
3,clubs,4
4,clubs,5
5,clubs,6
6,clubs,7
7,clubs,8
8,clubs,9
9,clubs,10


#### Student Practice
<u>Finish the rest of the notebook yourself.</u> Then check your answers as I walk through the solutions. 

Let's now use `join` to add the correct wand to each Harry Potter character.

In [124]:
# first, view the wand data
wand.head()

,Wand
ID,
0,"11"" Holly phoenix feather"
1,"12"" Ash unicorn tail hair"
2,"10¾"" vine wood dragon heartstring"
3,"15"" Elder Thestral tail hair core"
4,"13"" Cherry unicorn hair"


The wand data contains the specific wand descriptions for each character in the Harry Potter dataset listed in ID order.

**Exercise**: Add the `wand` data as a column in the `hp_characters` dataset using the `join()` method.

In [136]:
### ENTER CODE HERE ###

hp_characters = hp_characters.join(wand)

Now let's take a look at the `color` dataframe. It lists the hair and eye color for each Harry Potter character.

In [130]:
# view color
color.head()

,Name,Hair colour,Eye colour
ID,,,
0,Harry James Potter,Black,Bright green
1,Ronald Bilius Weasley,Red,Blue
2,Hermione Jean Granger,Brown,Brown
3,Albus Percival Wulfric Brian Dumbledore,Silver| formerly auburn,Blue
4,Neville Longbottom,Blond,NaN


**Exercise:** Merge the `color` data with the `hp_characters` DataFrame using the `merge()` method.

In [138]:
### ENTER CODE HERE ###

hp_characters = pd.merge(hp_characters, color)

There is also data from non-Hogwart's House characters (ie those not in Gryffindor, Slytherin, Ravenclaw or Hufflepuff) but it has been separated into two different datasets. Let's take a look at them now.

In [ ]:
other1.head()

In [ ]:
other2.head()

**Exercise:** Using `merge()` combine the `other1` and `other2` data into a new dataframe called `other_characters` keeping the respective `ID` for each instance. (check the Pandas documentation if you need help)

In [140]:
### ENTER CODE HERE ###

other_characters = pd.merge(other1, other2, left_index=True, right_index=True)

##or...other_characters = pd.merge(other1, other2, Left_on = 'Name', right_on='Given Name').set_index(other1.index)


Notice that both `Name` and `Given Name` is in the new DataFrame. Since this is providing duplicate information you could now remove one of the columns. 

**Bonus Exercise:** Merge the `other1` and `other2` data the same as above but also removing the `Given Name` field. Try to do this in one line of code.

In [142]:
### ENTER CODE HERE ###

other_characters = pd.merge(other1, other2, left_index=True, right_index=True).drop('Given Name', axis = 1)
other_characters.head()

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Eye colour,Hair colour
ID,,,,,,,,,,
70,Cuthbert Binns,Male,Professor of History of Magic,NaN,Unknown,Ghost,NaN,Unknown,Black,White (balding)
71,Barty Crouch Jr.,Male,Professor of Defence Against the Dark Arts (as...,NaN,Unknown,Human,Pure-blood or half-blood,Unknown,"Pale, freckled",Straw blond
72,Charity Burbage,Female,Professor of Muggle Studies,NaN,Non-corporeal,Human,Pure-blood or half-blood,Unknown,NaN,Blonde
73,Firenze,Male,Professor of Divination,NaN,NaN,Centaur,NaN,NaN,Astonishingly blue,White-blond
92,Igor Karkaroff,Male,Headmaster of Durmstrang Institute,NaN,NaN,Human,Pure-blood or Half-blood,Unknown,NaN,Silver| formerly black


**Exercise:** Add `other_characters` to the `hp_characters` DataFrame.

In [144]:
### ENTER CODE HERE ###

hp_characters = pd.concat([hp_characters, other_characters])
hp_characters.head()

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,"11"" Holly phoenix feather",Black,Bright green
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,"12"" Ash unicorn tail hair",Red,Blue
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,"10¾"" vine wood dragon heartstring",Brown,Brown
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,"15"" Elder Thestral tail hair core",Silver| formerly auburn,Blue
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,"13"" Cherry unicorn hair",Blond,NaN


**Bonus Exercise**:

After merging all the data, we noticed a **big mistake**! Hagrid, one of our favorite characters, is missing from the data. Here is his information:

- **Name**: Rubeus Hagrid
- **Gender**: Male
- **Job**: Keeper of Keys and Grounds | Professor of Care of Magical Creatures
- **House**: Gryffindor
- **Patronus**: None
- **Species**: Half-Human/Half-Giant
- **Blood status**: Part-Human (Half-giant)
- **Wand**: 16" Oak unknown core
- **Hair colour**: Black
- **Eye colour**: Black

Add Hagrid to the `hp_characters` dataset. (try to Google how to do this if needed, then watch the solutions video for one option)

In [146]:
### ENTER CODE HERE ###
new_character = {'Name': 'Rebeus Hagrid', 'Gender': 'Male', 'Job': 'Keeper', 'House': 'Griffindor', 'Patronous': None,
                 'Species': 'Half-human', 'Blood Status': 'Part-Human', 'Wand': '16" Oak unknown core', 'Eye colour': 'Black',
                 'Hair colour': 'Black'}

new_character_df=pd.DataFrame(new_character, index=[139])

hp_characters = pd.concat([hp_characters, new_character_df])

hp_characters.tail()

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour,Patronous,Blood Status
135,Fenrir Greyback,Male,NaN,NaN,NaN,Werewolf,NaN,Unknown,Grey,NaN,NaN,NaN
136,Gellert Grindelwald,Male,Revolutionary leader(c. 1920s[6]  1945),NaN,NaN,Human,Pure-blood or half-blood,"15"", Elder, Thestral tail hair core",Blond,Blue,NaN,NaN
137,Dobby,Male,"Malfoy family's house-elf (? - 1993),\nHogwart...",NaN,NaN,House elf,NaN,NaN,Green,NaN,NaN,NaN
138,Kreacher,Male,"Black family's house-elf (?-1996), \nHarry Pot...",NaN,NaN,House elf,NaN,NaN,White,NaN,NaN,NaN
139,Rebeus Hagrid,Male,Keeper,Griffindor,NaN,Half-human,NaN,"16"" Oak unknown core",Black,Black,None,Part-Human


Next, view the `dead_characters` DataFrame which includes the date of death for any deceased characters.

In [148]:
# view dataframe
dead_characters.head()

,Name,Death
ID,,
3,Albus Percival Wulfric Brian Dumbledore,"30 June, 1997"
5,Fred Weasley,"2 May, 1998"
10,Lily J. Potter,"31 October, 1981"
11,James Potter,"31 October, 1981"
12,Sirius Black,"18 June, 1996"


**Exercise:** Create a DataFrame called `hp_dead_characters` by merging the `hp_characters` and `dead_characters` DataFrames. This new DataFrame should only include characters that are deceased. Don't worry about preserving index numbers.

In [150]:
### ENTER CODE HERE ###

hp_dead_characters = pd.merge(hp_characters, dead_characters, on='Name', how='right').set_index(dead_characters.index)


Next, look at the `loyalty` DataFrame. This includes a list of all characters with stated allegiance to Voldemort.

In [152]:
# view loyalty
loyalty.head()

,Name,Loyalty
ID,,
14,Peter Pettigrew,Lord Voldemort| Death Eaters
31,Quirinus Quirrell,Lord Voldemort
48,Bellatrix Lestrange,Lord Voldemort | Death Eaters
51,Lucius Malfoy,Lord Voldemort | Death Eaters
52,Narcissa Malfoy,Lord Voldemort | Death Eaters


**Exercise:** Create a DataFrame called `voldemort_army` that includes only characters loyal to Voldemort. Again, you don't need to preserve index numbers.

In [154]:
### ENTER CODE HERE ###
voldermort_army = pd.merge(hp_characters, loyalty, how='inner')

voldermort_army.head()


,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour,Patronous,Blood Status,Loyalty
0,Peter Pettigrew,Male,The Servant of Lord Voldemort,Gryffindor,NaN,Human,Half-blood or pure-blood,"9¼"" Chestnut dragon heartstring",Colourless and balding,Blue,NaN,NaN,Lord Voldemort| Death Eaters
1,Barty Crouch Jr.,Male,Professor of Defence Against the Dark Arts (as...,NaN,Unknown,Human,Pure-blood or half-blood,Unknown,Straw blond,"Pale, freckled",NaN,NaN,Lord Voldemort | Death Eaters
2,Fenrir Greyback,Male,NaN,NaN,NaN,Werewolf,NaN,Unknown,Grey,NaN,NaN,NaN,Lord Voldemort | Death Eaters


Now take a look at the `gryffindor_bloodstatus` and `gryffindor_species` dataframes.

In [156]:
gryffindor_bloodstatus.head()

,Name,Type
ID,,
0,Harry James Potter,Half-blood
1,Ronald Bilius Weasley,Pure-blood
2,Hermione Jean Granger,Muggle-born
3,Albus Percival Wulfric Brian Dumbledore,Half-blood
4,Neville Longbottom,Pure-blood


In [158]:
gryffindor_species.head()

,Name,Gender,Job,House,Type
ID,,,,,
0,Harry James Potter,Male,Student,Gryffindor,Human
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Human
2,Hermione Jean Granger,Female,Student,Gryffindor,Human
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Human
4,Neville Longbottom,Male,Student,Gryffindor,Human


**Exercise:** Merge these two DataFrames together into a new DataFrame called `gryffindor2`. Notice that they both have a column called `Type` that represents different attributes. Add a suffix to the `Type` attributes so we better understand what each attribute represents.

In [164]:
### ENTER CODE HERE ###

gryffindor2 = pd.merge(gryffindor_bloodstatus, gryffindor_species, on = 'Name', suffixes=('_bloodstatus', '_species')).head()

gryffindor2.head()

,Name,Type_bloodstatus,Gender,Job,House,Type_species
0,Harry James Potter,Half-blood,Male,Student,Gryffindor,Human
1,Ronald Bilius Weasley,Pure-blood,Male,Student,Gryffindor,Human
2,Hermione Jean Granger,Muggle-born,Female,Student,Gryffindor,Human
3,Albus Percival Wulfric Brian Dumbledore,Half-blood,Male,Headmaster,Gryffindor,Human
4,Neville Longbottom,Pure-blood,Male,Student,Gryffindor,Human


### Removing Columns

Now that we've had practice adding columns and merging dataframes. Let's practice removing columns.

In [168]:
# refresh DataFrame
hp_characters.head()

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour,Patronous,Blood Status
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,"11"" Holly phoenix feather",Black,Bright green,NaN,NaN
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,"12"" Ash unicorn tail hair",Red,Blue,NaN,NaN
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,"10¾"" vine wood dragon heartstring",Brown,Brown,NaN,NaN
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,"15"" Elder Thestral tail hair core",Silver| formerly auburn,Blue,NaN,NaN
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,"13"" Cherry unicorn hair",Blond,NaN,NaN,NaN


**Exercise:** Since the `Skills` column is mostly filled with null values, remove this column from the `hp_characters` DataFrame.

In [166]:
### ENTER CODE HERE ###

hp_characters = hp_characters.drop('Skills', axis=1)


KeyError: "['Skills'] not found in axis"

### Updating Value in DataFrame

Notice that some values are labeled with a `?`. These are values where the data is unknown...in other words, the books or movies never mention it.

In [170]:
# see Fred and George Weasley's Patronus column as an example
hp_characters.head(10)

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour,Patronous,Blood Status
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,"11"" Holly phoenix feather",Black,Bright green,NaN,NaN
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,"12"" Ash unicorn tail hair",Red,Blue,NaN,NaN
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,"10¾"" vine wood dragon heartstring",Brown,Brown,NaN,NaN
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,"15"" Elder Thestral tail hair core",Silver| formerly auburn,Blue,NaN,NaN
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,"13"" Cherry unicorn hair",Blond,NaN,NaN,NaN
5,Fred Weasley,Male,Student,Gryffindor,?,Human,Pure-blood,Unknown,Red,Brown,NaN,NaN
6,George Weasley,Male,Student,Gryffindor,?,Human,Pure-blood,Unknown,Red,Brown,NaN,NaN
7,Ginevra (Ginny) Molly Weasley,Female,Student,Gryffindor,Horse,Human,Pure-blood,Unknown,Red,Bright brown,NaN,NaN
8,Dean Thomas,Male,Student,Gryffindor,?,Human,Muggle-born,Unknown,Black,Brown,NaN,NaN
9,Seamus Finnigan,Male,Student,Gryffindor,Fox,Human,Half-blood,Unknown,Sandy,NaN,NaN,NaN


**Exercise:** Change all values of `?` to the string `'Unknown'` to better represent what this data means.

In [174]:
### ENTER CODE HERE ###
hp_characters = hp_characters.replace('?', 'Unknown')
hp_characters.head(10)

,Name,Gender,Job,House,Patronus,Species,Blood status,Wand,Hair colour,Eye colour,Patronous,Blood Status
0,Harry James Potter,Male,Student,Gryffindor,Stag,Human,Half-blood,"11"" Holly phoenix feather",Black,Bright green,NaN,NaN
1,Ronald Bilius Weasley,Male,Student,Gryffindor,Jack Russell terrier,Human,Pure-blood,"12"" Ash unicorn tail hair",Red,Blue,NaN,NaN
2,Hermione Jean Granger,Female,Student,Gryffindor,Otter,Human,Muggle-born,"10¾"" vine wood dragon heartstring",Brown,Brown,NaN,NaN
3,Albus Percival Wulfric Brian Dumbledore,Male,Headmaster,Gryffindor,Phoenix,Human,Half-blood,"15"" Elder Thestral tail hair core",Silver| formerly auburn,Blue,NaN,NaN
4,Neville Longbottom,Male,Student,Gryffindor,Non-corporeal,Human,Pure-blood,"13"" Cherry unicorn hair",Blond,NaN,NaN,NaN
5,Fred Weasley,Male,Student,Gryffindor,Unknown,Human,Pure-blood,Unknown,Red,Brown,NaN,NaN
6,George Weasley,Male,Student,Gryffindor,Unknown,Human,Pure-blood,Unknown,Red,Brown,NaN,NaN
7,Ginevra (Ginny) Molly Weasley,Female,Student,Gryffindor,Horse,Human,Pure-blood,Unknown,Red,Bright brown,NaN,NaN
8,Dean Thomas,Male,Student,Gryffindor,Unknown,Human,Muggle-born,Unknown,Black,Brown,NaN,NaN
9,Seamus Finnigan,Male,Student,Gryffindor,Fox,Human,Half-blood,Unknown,Sandy,NaN,NaN,NaN


### Renaming Columns

The data has the British spelling for colour. Since this data will be used in the US, we should rename these columns.

**Exercise:** Rename the word `colour` to `color` in the respective columns for the `hp_characters` dataframe.

In [176]:
### ENTER CODE HERE ###
hp_characters = hp_characters.rename({'Hair Colour': 'Hair Color', 'Eye Colour': 'Eye Color'}, axis=1)

### Perform DataFrame Operation for New Column

Let's setup a new DataFrame called `hp_characters_new` that contains information about some of our favorite characters.

In [178]:
# data for new dataframe
data = {'Name': ['Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Ginny Weasley', 'Rubeus Hagrid','Neville Longbottom'], 
            'Job': ['Student', 'Student','Student','Student','Keeper of Keys and Grounds','Student'],
            'House': ['Gryffindor','Gryffindor','Gryffindor','Gryffindor','Gryffindor','Gryffindor'],
            'Birth Year': [1980,1980,1979,1980,1928,1980]}

# create new dataframe with the above data
hp_characters_new = pd.DataFrame(data)
hp_characters_new

,Name,Job,House,Birth Year
0,Harry Potter,Student,Gryffindor,1980
1,Ron Weasley,Student,Gryffindor,1980
2,Hermione Granger,Student,Gryffindor,1979
3,Ginny Weasley,Student,Gryffindor,1980
4,Rubeus Hagrid,Keeper of Keys and Grounds,Gryffindor,1928
5,Neville Longbottom,Student,Gryffindor,1980


**Bonus Exercise:** Add a new column called `Age` that tells how old each character would be if they were 'alive' today.

In [180]:
### ENTER CODE HERE ###

import datetime

current_year = datetime.datetime.now().year
hp_characters_new['Age'] = current_year - hp_characters_new['Birth Year']
hp_characters_new.head()

,Name,Job,House,Birth Year,Age
0,Harry Potter,Student,Gryffindor,1980,45
1,Ron Weasley,Student,Gryffindor,1980,45
2,Hermione Granger,Student,Gryffindor,1979,46
3,Ginny Weasley,Student,Gryffindor,1980,45
4,Rubeus Hagrid,Keeper of Keys and Grounds,Gryffindor,1928,97


## combine_first
Pandas' `combine_first` method is used to combine two DataFrames by filling in missing values (NaNs) in one DataFrame with values from another DataFrame. Essentially, it "fills in the blanks" from the first DataFrame with corresponding values from the second DataFrame.

Here's a simple example to illustrate:

Imagine you have two DataFrames, `df1` and `df2`. `df1` has some missing values (NaNs), and you want to fill these missing values using the data from `df2`.

In [182]:
#Create the first DataFrame with some missing values
df1 = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [None, 2, 3, 4]
})

# Create the second DataFrame with values that will be used to fill df1
df2 = pd.DataFrame({
    'A': [5, 6, 7, 8],
    'B': [1, None, 3, 4]
})

In [184]:
df1

,A,B
0,1.0,NaN
1,2.0,2.0
2,NaN,3.0
3,4.0,4.0


In [186]:
df2

,A,B
0,5,1.0
1,6,NaN
2,7,3.0
3,8,4.0


In [188]:
#Combine df1 and df2 using combine_first
result = df1.combine_first(df2)
result

,A,B
0,1.0,1.0
1,2.0,2.0
2,7.0,3.0
3,4.0,4.0


In [192]:
hp_characters.value_counts('Gender'=='Male')

KeyError: False

Use `combine_first` when you have two DataFrames and you want to fill in the missing values in the first DataFrame with the values from the second DataFrame. This is particularly useful when dealing with incomplete datasets where you have a secondary source of data that can provide the missing information.

### Other Questions

For further practice with data analysis, here are some additional questions to try to answer on your own.

- How many of the characters are female are there in the `hp_characters` DataFrame? How many of the characters are male?
- How many characters are there of each respective house?
- What are the various species represented in the dataset?
- List the various value counts for blood status.
- What job is the most represented in the data?